export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

    SET_USERS: "SET_USERS",
    SELECTED_USER: "SELECTED_USER",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER"
}